[tool.poetry]
name = "form-lang-ml"
version = "0.1.0"
description = ""
authors = ["Guy Or <guydude1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jupyter = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
