export const RANDOM_JS_EXPRESSIONS = [
  "1 + 2 * 3",
  "'hello' + ' world'",
  "5 > 10",
  "Math.random()",
  "true || false",
  "10 % 3",
  "2 ** 4",
  "Math.max(5, 10, 2)",
  "'Hello'.toLowerCase()",
  "parseInt('123')",
  "new Date()",
  "typeof 'hello'",
  "null === undefined",
  "isNaN('abc')",
  "[1, 2, 3].length",
  "({name: 'John'}).name",
  "Array.isArray([1, 2])",
  "10 < 20 ? 'yes' : 'no'",
  "function greet() { return 'Hello!'; }",
  "(a, b) => a + b",
  "'hello'.charAt(0)",
  "'hello'.indexOf('l')",
  "'  hello  '.trim()",
  "Math.floor(4.5)",
  "Math.ceil(4.2)",
  "Math.round(4.7)",
  "Math.abs(-5)",
  "Math.sqrt(16)",
  "Math.pow(2, 3)",
  "Math.PI",
  "Math.E",
  "JSON.stringify({name: 'John'})",
  "Object.keys({name: 'John', age: 30})",
  "Object.values({name: 'John', age: 30})",
  "new Set([1, 2, 2, 3])",
  "new Map([['name', 'John'], ['age', 30]])",
  "Promise.resolve('success')",
  "setTimeout(() => console.log('Hello'), 1000)",
  "setInterval(() => console.log('Hello'), 1000)",
  "clearTimeout()",
  "clearInterval()",
  "document.getElementById('myId')",
  "document.createElement('div')",
  "window.innerWidth",
  "window.innerHeight",
  "navigator.userAgent",
  "location.href",
  "console.log('Hello')",
  "console.error('Error')",
  "console.warn('Warning')",
  "alert('Hello')",
  "confirm('Are you sure?')",
  "prompt('Enter your name:')",
  "decodeURIComponent('%20')",
  "encodeURIComponent(' ')",
  "eval('1 + 2')",
  "isFinite(10)",
  "Number.isNaN(NaN)",
  "parseFloat('12.34')",
  "parseInt('123', 10)",
  "String(123)",
  "Number('123')",
  "Boolean(1)",
  "!!'hello'",
  "~10",
  "10 >> 1",
  "10 << 1",
  "10 >>> 1",
  "10 & 5",
  "10 | 5",
  "10 ^ 5",
  "10 && 5",
  "10 || 5",
  "!true",
  "void 0",
  "typeof null",
  "delete ({name: 'John'}).name",
  "('hello').constructor",
  "(123).toString()",
  "(123).toFixed(2)",
  "Math.random() * 100",
  "Math.floor(Math.random() * 100)",
  "Date.now()",
  "new Date().getFullYear()",
  "new Date().getMonth()",
  "new Date().getDate()",
  "new Date().getHours()",
  "new Date().getMinutes()",
  "new Date().getSeconds()",
  "'hello'.replace('l', 'L')",
  "'hello'.split('')",
  "'hello'.substring(1, 4)",
  "'hello'.toUpperCase()",
  "[1, 2, 3].join(', ')",
  "[1, 2, 3].pop()",
  "[1, 2, 3].push(4)",
  "[1, 2, 3].shift()",
  "[1, 2, 3].unshift(0)",
  "[1, 2, 3].slice(1, 3)",
  "[1, 2, 3].splice(1, 1)",
  "[1, 2, 3].reverse()",
  "[1, 2, 3].sort()",
  "[1, 2, 3].map(x => x * 2)",
  "[1, 2, 3].filter(x => x > 1)",
  "[1, 2, 3].reduce((a, b) => a + b, 0)",
];
